name: dl-toolbox
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
- packaging
- numpy
- imageio
- imageio-ffmpeg
#old: - frozendict
- pyqt
#- matplotlib
#- opencv
#- keras
#- tensorflow-gpu
#- pytorch
#- torchvision
#- mtcnn
#- gtk3
#- pygobject
#- appdirs
#- imutils
#- gitpython
#- tqdm
# Tools:
- jupyter