name: dl-toolbox
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
- python
- packaging
- numpy
- matplotlib
- imageio
- imageio-ffmpeg
- ipython
- jupyter
- tensorflow-gpu
- pytorch
- torchvision
- torchaudio
- pysoundfile
- python-sounddevice
- librosa
- pyqt
- pip
